# Generated by Django 6.0.3 on 2026-03-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_gst_invoice_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
